#!/bin/sh
# Writes TaDo/Config/Secrets.swift (git-ignored) from the web app's .env.local,
# so both apps talk to the same Supabase project. The anon key is public by design —
# data is protected by RLS — but it's kept out of git the same way the web app does.
set -e
cd "$(dirname "$0")/.."
ENV_FILE="../.env.local"
url=$(grep '^VITE_SUPABASE_URL=' "$ENV_FILE" | cut -d= -f2-)
key=$(grep '^VITE_SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d= -f2-)
if [ -z "$url" ] || [ -z "$key" ]; then
  echo "VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY missing from $ENV_FILE" >&2
  exit 1
fi
cat > TaDo/Config/Secrets.swift <<SWIFT
// Generated by scripts/write-secrets.sh — do not commit.
enum Secrets {
    static let supabaseURL = "$url"
    static let supabaseAnonKey = "$key"
}
SWIFT
echo "Wrote TaDo/Config/Secrets.swift"
